### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by lingzhenfei123** [waczjoan/gaussian-mesh-splatting#35]
Traceback (most recent call last):
  File "train.py", line 264, in <module>
    training(
  File "train.py", line 100, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
  File "/home/Meshgs/gaussian-mesh-splatting/renderer/gaussian_renderer/__init__.py", line 104, in render
    rendered_image, radii, depth_image = rasterizer(
  File "/root/anaconda3/envs/gaussian_splatting_mesh/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/gaussian_splatting_mesh/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 197, in forward
    return rasterize_gaussians(
  File "/root/anaconda3/envs/gaussian_splatting_mesh/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 32, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/root/anaconda3/envs/gaussian_splatting_mesh/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/anaconda3/envs/gaussian_splatting_mesh/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 84, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer, invdepths = _C.rasterize_gaussians(*args)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 130064.36 GiB (GPU 0; 39.39 GiB total capacity; 2.22 GiB already allocated; 35.08 GiB free; 3.01 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by piotr310100** [comment]
Hi,
It seems like you're encountering an issue with CUDA. The 130064GiB allocation appears quite unusual considering the requested size.
Could you please clarify the following?
1. Have you tried running vanilla Gaussian splatting on your dataset? Does the code work properly in that case?
2. Can you provide more details on how to reproduce the error?
Thanks!

**Comment by lingzhenfei123** [comment]
Hi,
I ran my dataset on vanilla Gaussian splatting, and it works correctly.
The dataset structure is as follows:
hotdog
--test
--train
--val
mesh.obj
transforms_test.json
transforms_train.json
transforms_val.json
The mesh.obj file comes from https://github.com/gaoxiangjun/Mani-GS?tab=readme-ov-file.
I encountered an error when running the command train.py --eval -s /data/hotdog -m output/hotdog_gs_mesh --gs_type gs_mesh -w.
Thanks!

**Comment by piotr310100** [comment]
Hi,
I tried reproducing the error using a mesh provided by the authors of Mani-GS here https://github.com/gaoxiangjun/Mani-GS?tab=readme-ov-file#-training-and-evaluation. I've downloaded the mesh_poi_clean.ply, converted it to mesh.obj using blender 4.0 and trained the model using the following command:
python train.py --eval -s ~/data/hotdog -m output/hotdog_gs_mesh --gs_type gs_mesh -w
I was able to complete the training without errors. 

1. Can you check if this approach works?
2. Have you done anything differently?

**Comment by lingzhenfei** [comment]
Hi, have you made any modifications to the code? I still encounter the issue when running the code as mentioned above.
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    training(
  File "train.py", line 100, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
  File "/home/Meshgs/gaussian-mesh-splatting/renderer/gaussian_renderer/__init__.py", line 187, in render
    rendered_image, radii, depth_image = rasterizer(
  File "/root/anaconda3/envs/gaussian_splatting_mesh/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/gaussian_splatting_mesh/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 197, in forward
    return rasterize_gaussians(
  File "/root/anaconda3/envs/gaussian_splatting_mesh/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 32, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/root/anaconda3/envs/gaussian_splatting_mesh/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/anaconda3/envs/gaussian_splatting_mesh/lib/python3.8/site-packages/diff_gaussian_rasterization/__init__.py", line 84, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer, invdepths = _C.rasterize_gaussians(*args)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 130764.66 GiB (GPU 0; 39.39 GiB total capacity; 2.50 GiB already allocated; 34.87 GiB free; 3.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by piotr310100** [comment]
Hi, sorry for the late response. I haven't made any changes to the code. Have you used the mesh obtained from mesh_poi_clean.ply or one of the others?
